### ISSUE TITLE
[Weekly Report] 11월 3일

### ISSUE THREAD

**Issue by csy1204** [csy1204/Capstone-project-2020-Fall#7]
## Milestone 
- 데이터 전처리 
- 모델 하나 돌려서 성능을 확인 
- `Decision Tree`

### 조영민
- [x] Tag similarity 분석

### 진승현
- [x] Latent Factor CF
- [ ] LigthGBM

### 조상연
- [x] 학습 데이터 생성
- [ ] 네거티브 샘플링

## TIL
- https://github.com/gyubok-lee/kakao_music_recommendation
